RentiMerito/Models/ErrorViewModel.cs
namespace RentiMerito.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RentiMerito/Controllers/CarsController.cs
using Domain.Services.Cars;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Routing;

namespace RentiMerito.Controllers
{
    public class CarsController : Controller
    {
        private readonly ICarService _carService;

        public CarsController(ICarService carService)
        {
            _carService = carService;
        }

        public IActionResult Index()
        {
            var cars = _carService.GetNonRentedCars();
            return View(cars);
        }

        public IActionResult CarDetails(int carId)
        {
            var car = _carService.GetCarById(carId);
            return View(car);
        }
    }
}

RentiMerito/Controllers/HomeController.cs
using Domain.Services.Cars;
using Microsoft.AspNetCore.Mvc;
using RentiMerito.Models;
using System.Diagnostics;

namespace RentiMerito.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ICarService _carService;

        public HomeController(ILogger<HomeController> logger, ICarService carService)
        {
            _logger = logger;
            _carService = carService;
        }

        public IActionResult Index()
        {
            var cars = _carService.DisplaySixCars();
            return View(cars);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RentiMerito/Controllers/RentController.cs
using Domain.Services.Cars;
using Microsoft.AspNetCore.Mvc;

namespace RentiMerito.Controllers
{
    public class RentController : Controller
    {
        private readonly ICarService _carService;

        public RentController(ICarService carService)
        {
            _carService = carService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult RentCar()
        {
            return View();
        }

        public IActionResult RentableCars(string city, DateTime startDate, DateTime endDate)
        {
            var rentableCars = _carService.GetRentableCars(city, startDate, endDate);
            return View(rentableCars);
        }
    }
}

RentiMerito/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RentiMerito</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RentiMerito.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">RentiMerito</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - RentiMerito - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

RentiMerito/Views/Cars/CarDetails.cshtml
@model Domain.Models.Cars.CarModel;

<h1>This is kurwa @Model.CarBrand @Model.CarName pif paf</h1>

RentiMerito/Views/Cars/Index.cshtml
@model List<Domain.Models.Cars.CarModel>

@foreach (var car in Model)
{
    await Html.RenderPartialAsync("../Shared/_CarCard.cshtml", car);
}

RentiMerito/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model List<Domain.Models.Cars.CarModel>;

<div class="text-center">
    <h4 class="display-4">Rent a car</h4>
    <div class="round-shadow">
        <form asp-controller="Rent" asp-action="RentableCars" method="post">
            <div class="mb-3">
                <input type="text" class="form-control" name="city" id="city" placeholder="Pickup City" />
            </div>
            <div class="mb-3">
                <label>Rent Start</label>
                <input type="date" class="" name="startDate" id="startDate" />
                <label>Rent End</label>
                <input type="date" class="" name="endDate" id="endDate" />
            </div>
            <div class="mb-3">
                <input type="checkbox" class="form-check-input" name="checkAge" id="checkAge" />
                <label for="checkAge" class="form-check-label">Driver age between 30-65</label>
            </div>
            <input type="submit" class="btn btn-warning"value="Search" />
        </form>
    </div>
    <br />
    <div>
        <div class="card-group">
            @foreach (var car in Model)
            {
                <div class="card card-margin">
                    <div class="card-title">
                        <p>@car.CarBrand @car.CarName</p>
                    </div>
                    <img src="@car.CarImage" alt="@car.CarName" class="card-img-bottom" />
                    <p class="card-text">$200</p>
                    <button id="@car.CarId" class="btn btn-warning">@Html.ActionLink("More!", "CarDetails", "Cars", new { carId = car.CarId })</button>
                </div>
            }
        </div>
    </div>
</div>

<style>
    .card-margin
    {
        margin-left: 5px;
        margin-right: 5px;
    }
    .round-shadow
    {
        border-radius: 5px;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        padding: 5px;
    }
</style>

RentiMerito/Views/Rent/Index.cshtml
<form asp-controller="Rent" asp-action="RentableCars" method="post">
    <div class="mb-3">
        <input type="text" class="form-control" name="city" id="city" placeholder="Pickup City" />
    </div>
    <div class="mb-3">
        <label>Rent Start</label>
        <input type="date" class="" name="startDate" id="startDate" />
        <label>Rent End</label>
        <input type="date" class="" name="endDate" id="endDate" />
    </div>
    <div class="mb-3">
        <input type="checkbox" class="form-check-input" name="checkAge" id="checkAge" />
        <label for="checkAge" class="form-check-label">Driver age between 30-65</label>
    </div>
    <input type="submit" class="btn btn-warning" value="Search" />
</form>

RentiMerito/Views/Rent/RentableCars.cshtml
@model List<Domain.Models.Cars.CarModel>;
@if(Model.Count <= 0)
{
    <h5 style="color: red">No cars found for the provided city in those dates!</h5>
}
else
{
    @foreach(var car in Model)
    {
        await Html.RenderPartialAsync("../Shared/_CarCard.cshtml", car);
    }
}

RentiMerito/Views/Shared/_CarCard.cshtml
@model Domain.Models.Cars.CarModel;

<div class="card mb-3" style="max-width: 540px;">
    <div class="row g-0">
        <div class="col-md-4">
            <img src="@Model.CarImage" class="img-fluid rounded-start" alt="@Model.CarName">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">@Model.CarBrand @Model.CarName</h5>
                <p class="card-text">$200</p>
                <button id="@Model.CarId" class="btn btn-warning">@Html.ActionLink("More!", "CarDetails", "Cars", new { carId = @Model.CarId })</button>
            </div>
        </div>
    </div>
</div>

RentiMerito/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RentiMerito</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RentiMerito.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RentiMerito</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Rent" asp-action="Index">Rent</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cars" asp-action="Index">All Cars</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Contact</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - RentiMerito by Oskar Alchimowicz & Adrian Barabasz - <a asp-area="" asp-controller="Home" asp-action="Privacy">Contact</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>